name: TypeScript Check
on:
  pull_request:
jobs:
  run-tsc-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Generate Prisma client
        run: npx prisma generate
      - name: Run tsc check
        run: npm run tsc:check
